### ISSUE TITLE
Don't install when connecting

### ISSUE THREAD

**Issue by vmx** [hugomrdias/connect-deps#1]
When running `link` it also automatically installs the package.

I think a cleaner workflow would be to always need to run:

```console
$ connect-deps link ../somepath
$ connect connect
```

This way linking is fast and you could link several one quickly and only have a single slow `connect` run.

Perhaps there could also be a `--connect` option for `link` that resembles the current bahaviour.

**Comment by hugomrdias** [comment]
i agree
