### ISSUE TITLE
If two changes happen at the same time, only one triggeres a rebuild

### ISSUE THREAD

**Issue by vmx** [hugomrdias/connect-deps#12]
If you change files in two linked project at the same time, only one dependency triggers a rebuild.

Steps to reproduce:

```console
$ /home/vmx/src/pl/misc/connect-deps/cli.js link ../js-ipfs-unixfs-exporter ../js-ipfs-unixfs-importer
✔ Linking ../js-ipfs-unixfs-exporter
✔ Linking ../js-ipfs-unixfs-importer
$ /home/vmx/src/pl/misc/connect-deps/cli.js connect  --watch
Watching in /tmp/mfsyarn/js-ipfs-unixfs-exporter for **/*
Watching in /tmp/mfsyarn/js-ipfs-unixfs-importer for **/*
```

In another terminal:

```console
touch js-ipfs-unixfs-exporter/foo js-ipfs-unixfs-importer/foo
```

The only output will be:

```console
✔ Packing ipfs-unixfs-importer
✔ Installing dependencies: file:/tmp/mfsyarn/js-ipfs-mfs/.connect-deps-cache/ipfs-unixfs-importer-0.39.11-1564589573364.tg
```

It's missing the ipfs-unixfs-exporter change.

**Comment by hugomrdias** [comment]
can you move this line https://github.com/hugomrdias/connect-deps/blob/69efcd929d3603b2031ca849c203df702569577a/cli.js#L158 inside the for in loop and see if it fixes this issue ?

**Comment by vmx** [comment]
It does! Now it totally works as I'd expect it to work.
