### ISSUE TITLE
Add option to not link dev dependencies

### ISSUE THREAD

**Issue by achingbrain** [hugomrdias/connect-deps#14]
```
- Linking ..path
✔ Linking ..path
npx: installed 251 in 15.965s
- Packing ipfs
✔ Packing ipfs
- Installing dev dependencies: file:/path/.connect-deps-cache/module-1568790355324.tgz
✔ Installing dev dependencies: file:/path/.connect-deps-cache/module-1568790355324.tgz
```

Can there please be an option to not install dev dependencies?

**Comment by hugomrdias** [comment]
that's because you linked a dev dependency
https://github.com/hugomrdias/connect-deps/blob/master/cli.js#L271-L280

**Comment by achingbrain** [comment]
Aha, from the message I though that meant it was installing the dev dependencies of the linked module.  I guess that's not the case.
