### ISSUE TITLE
Does not work when linked dep is not in package.json

### ISSUE THREAD

**Issue by satazor** [hugomrdias/connect-deps#16]
The use-case is when you are creating a new package and testing it, you would normally link it. However, if that new package which is not yet published is not present in package.json, `connect-deps` will simply ignore it.

**Comment by hugomrdias** [comment]
can't you add this new package to the package.json with local path ?

**Comment by pcowgill** [comment]
@satazor It seems like you always would want the package in `package.json`, even in the case you mentioned. So is this issue about documenting that that needs to be done manually? Or were you hoping this package would automatically add it?

**Comment by hugomrdias** [comment]
Actually connect-deps already supports unpublished packages and packages that are not in the package.json. 
I will keep this open to as a reminder to reference this in the readme.
