### ISSUE TITLE
Put .connect-deps-cache into the source project directory

### ISSUE THREAD

**Issue by vmx** [hugomrdias/connect-deps#2]
Currently every package that you link to gets a `.connect-deps-cache` directory created. I would prefer if that directory is part of the project where I initiated the linking from. I think the packages that you link to should be kept untouched to make sure they are really the same as you would `npm install` them.

This way linking would even work on packages where only have read access to.

This change would also make the cleanup easier/less error-prone as you would need to remove only a single directory and not one for every linked package.

**Comment by hugomrdias** [comment]
i agree
