### ISSUE TITLE
reset doesn't reset to original version

### ISSUE THREAD

**Issue by vmx** [hugomrdias/connect-deps#3]
When calling `connect-deps reset` it resets the package to the version the linked package had and not to the original version the `package.json` file had.

I think a proper fix would be to read in the original `package.json` and preserve the version string for resetting it.

**Comment by hugomrdias** [comment]
really ? 
this https://github.com/hugomrdias/connect-deps/blob/2a0c9e01af9bc4faae37c66d612b969ee3582751/cli.js#L70 doesn't do that ?

**Comment by vmx** [comment]
This is still an issue. Here are the steps to reproduce (I used npm).

```console
$ git clone https://github.com/ipfs/js-ipfs-mfs --branch v0.12.0
…
$ git clone https://github.com/ipfs/js-ipfs-unixfs-importer --branch v0.39.11
…
$ git clone https://github.com/ipfs/js-ipfs-unixfs-exporter --branch v0.37.7
…
$ cd js-ipfs-mfs
$ /home/vmx/src/pl/misc/connect-deps/cli.js link ../js-ipfs-unixfs-importer ../js-ipfs-unixfs-exporter
✔ Linking ../js-ipfs-unixfs-importer
✔ Linking ../js-ipfs-unixfs-exporter
$ /home/vmx/src/pl/misc/connect-deps/cli.js connect
✔ Packing ipfs-unixfs-importer
✔ Packing ipfs-unixfs-exporter
✔ Installing dependencies: file:/tmp/resetbug/js-ipfs-mfs/.connect-deps-cache/ipfs-unixfs-importer-0.39.11-1564745336554.tgz file:/tmp/resetbug/js-ipfs-mfs/.connect-deps-cache/ipfs-unixfs-exporter-0.37.7-1564745336952.tgz
$ /home/vmx/src/pl/misc/connect-deps/cli.js reset
✔ Resetting normal dependencies:  ipfs-unixfs-importer@~0.39.9 ipfs-unixfs-exporter@~0.37.6
✔ Cleaning up
$ git diff
diff --git a/package.json b/package.json
index fa733c4..ed64186 100644
--- a/package.json
+++ b/package.json
@@ -61,8 +61,8 @@
     "interface-datastore": "~0.6.0",
     "ipfs-multipart": "~0.1.0",
     "ipfs-unixfs": "~0.1.16",
-    "ipfs-unixfs-exporter": "~0.37.6",
-    "ipfs-unixfs-importer": "~0.39.9",
+    "ipfs-unixfs-exporter": "^0.37.7",
+    "ipfs-unixfs-importer": "^0.39.11",
     "ipld-dag-pb": "~0.17.2",
     "joi-browser": "^13.4.0",
     "mortice": "^1.2.1",
```

I propose that we parse the package.json file and replace the version directly there and then do an `npm install` without any arguments. I tried that locally and it seems to work.

**Comment by hugomrdias** [comment]
I would like to avoid changing package.json manually. Is there any flag on the yarn/npm cli that help with this?

**Comment by hugomrdias** [comment]
Wow it changed the symbol didn't notice that at first...
Yarn does the same thing ?

**Comment by hugomrdias** [comment]
Can you make sure you have the latest version of npm and yarn ?

**Comment by vmx** [comment]
I happens with the latest npm version (I haven't tried yarn).

Though I think manipulating the package.json would be the right behaviour. If you have a certain version range in your package.json, and you do an `npm install package@version-range` it will of course install the latest version. As you have run `install` it will also update the package.json. So it is the correct behaviour.

When manipulating the package.json directly, it will also take (hopefully) the package-lock.json correctly into account.

**Comment by vmx** [comment]
I can still reproduce the issue with the exact same steps. My npm version is `6.13.4`.

**Comment by hugomrdias** [comment]
i added information about this in the readme linked to this issue. i really don't want to manipulate the package.json manually the complexity of a fix doesn't bring enough value when you can just ignore the change before committing .
