### ISSUE TITLE
The commit message linting is losing commit messages

### ISSUE THREAD

**Issue by vmx** [hugomrdias/connect-deps#4]
If a commit message doesn't conform to the commit message rules, the commit message is lost. This is a problem when you write a long explanatory commit message that is gone without further notice.

**Comment by hugomrdias** [comment]
wow really is this a husky problem ?

**Comment by hugomrdias** [comment]
old issue gonna close this, feel free to reopen

**Comment by vmx** [comment]
It's still the case. Steps to reproduce:

```console
$ touch foo
$ git add foo
$ git commit
…
Type in some commit message that doesn't conform to linting rules and save it

husky > commit-msg (node v10.18.1)
⧗   input: Type in some commit message that doesn't conform to linting rules and save it
✖   header must not be longer than 72 characters, current length is 77 [header-max-length]
✖   subject may not be empty [subject-empty]
✖   type may not be empty [type-empty]

✖   found 3 problems, 0 warnings
ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint

husky > commit-msg hook failed (add --no-verify to bypass)
```

**Comment by hugomrdias** [comment]
its a husky issue @vmx can't fix it here

**Comment by vmx** [comment]
You could check the commit messages e.g. on pre-push instead of pre-commit.

**Comment by vmx** [comment]
Or using something like https://github.com/commitizen/cz-cli which helps preventing invalid messaged (it even has a [retry mode](https://github.com/commitizen/cz-cli#retrying-failed-commits)).

**Comment by vmx** [comment]
I've a better idea which isn't much work. Print out information on how to recover the commit message. Something like:

```
"commit-msg": "commitlint -E HUSKY_GIT_PARAMS || echo 'Your commit message is not lost! Try again with `git commit --edit --file=$(git rev-parse --show-toplevel)/.git/COMMIT_EDITMSG`"
```

I'm still on it to make it actually work. I just wanted to post now as I think that's the simplest solution and better than the other ones proposed.
